### ISSUE TITLE
Implement clinical reminders using the Flags module in OpenMRS

### ISSUE THREAD

**Issue by johnhaskew** [uamuzibora/nafasi#1]
Flags allows clinical reminders to be displayed on the dashboard. It uses custom SQL queries to identify patients and display appropriate messages.
https://wiki.openmrs.org/display/docs/Patient+Flags+Module

We can use this system to evaluate the use of clinical reminders to improve clinical decision support in HIV patients.

Please refer to [the wiki](https://github.com/uamuzibora/nafasi/wiki/Clinical-reminders) for a complete list of reminders that need to be implemented with corresponding SQL queries.
##### Recent Chest X-ray

Pseudocode:

```
IF NO CHEST X-RAY ON RECORD FOR PAST SIX MONTHS:
    REMINDER: PLEASE ORDER CHEST X-RAY (NO CXR ON RECORD FOR PAST SIX MONTHS)
```

SQL query:

``` sql
select distinct p.patient_id from obs observation inner join patient p /
on observation.person_id = p.patient_id /
where not exists ( /
select * from obs o where o.concept_id = 12 /
and o.obs_datetime > subdate(now(), 180) /
and o.obs_datetime < now() /
and observation.person_id = o.person_id);
```
##### CD4 count fallen below limit

Pseudocode:

```
IF CD4 COUNT <100 CELLS/MM3 AT MOST RECENT CLINIC VISIT:
    REMINDER: PLEASE LOOK CLOSER (CD4 <100 CELLS/MM3 AT MOST RECENT CLINIC VISIT)
```

SQL query:

``` sql
select distinct p.patient_id from obs o inner join patient p /
on o.person_id = p.patient_id /
inner join (select person_id, max(obs_datetime) as max_datetime /
from obs where concept_id = 5497 group by person_id) /
maximum on o.person_id = maximum.person_id /
and o.obs_datetime = maximum.max_datetime /
where o.value_numeric < 100;
```

**Comment by kenners** [comment]
I've created individual issues for each clinical reminder we wish to implement (as detailed in [the wiki](https://github.com/uamuzibora/nafasi/wiki/Clinical-reminders)).

If we require further clinical reminders or wish to change/amend those that have already been created, please create a new issue/update the appropriate issue.

If adding a new issue for a clinical reminder, remember to reference this issue by including `#1` somewhere in the issue body.

**Comment by kenners** [comment]
**Not done** during July 2012 visit due to lack of time.

We ought to reschedule this for September.

@Gulfa, @johnhaskew, @andrewlkho: Anyone want to take the lead on this?
