### ISSUE TITLE
Operational Research Questions - Enrollment

### ISSUE THREAD

**Issue by johnhaskew** [uamuzibora/nafasi#16]
Please note as part of a study to evaluate the ability of uamuzi bora to improve provision of care, clinical reminders will only to shown to a subset of patients in the database (whom we can enroll into a program called "clinical decision support research" for example). We can then compare outcomes among those receiving reminders and those not.

We would therefore need the sql statements listed here to show reminders only to patients enrolled in "clinical decision support research" program.

Please also note this is how we will enrol patients into a nested cohort study within LifeStraw health outcomes. This cohort of patients (n = 250 LifeStraw users and 250 non-users) will be intensively followed up in the home for episodes of diarrhoea and stool specimens will be taken and sent for laboratory diagnosis.

We therefore need to enrol 250 LifeStraw users and 250 non-users at clinic appointment into a program called "laboratory research" who can then be followed up at the home in this nested cohort study.

**Comment by kenners** [comment]
@johnhaskew: We should probably rephrase this issue and/or split it into subtasks over a conference call.
