### ISSUE TITLE
Create Ubuntu apt repo VM in EC2/VMware

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#17]
We need a VM to serve as an apt repo for Ubuntu 12.04 LTS server x64 edition to configure our server when we're in country.

I suggest we create an EC2 image and then export it using Amazon's ec2 export function into a VMWare image.

Suggest we use EC2's stock 64bit Ubuntu 12.04 image and install [apt-mirror](http://apt-mirror.sourceforge.net) and go from there.

**Comment by andrewlkho** [comment]
As discussed lets put these on two (duplicate) of these: [SanDisk 16GB USB drive](http://www.amazon.co.uk/SanDisk-Cruzer-Blade-Flash-Drive/dp/B002U1ZBG0).

**Comment by kenners** [comment]
As discussed, please include packages to handle compression and extraction of tar, bzip2, zip and 7z archives.

**Comment by andrewlkho** [comment]
A few notes to myself:
- apt-cacher looks to be the most promising way to do this
- In VirtualBox, set the networking type to Bridged

**Comment by kenners** [comment]
@andrewlkho used apt-cacher in the end with good effect. (Still requires a net connection though, as does not cache the apt repo index required when doing `apt-get update`).
