### ISSUE TITLE
Fix Tomcat memory leak when deploying

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#18]
Probably needs something like this  in <TOMCAT HOME>/conf/web.xml file under in the JSP servlet definition:

``` xml
<init-param>
    <param-name>enablePooling</param-name>
    <param-value>false</param-value>
</init-param>
```

More details at https://wiki.openmrs.org/display/docs/Troubleshooting+Memory+Errors

**Comment by andrewlkho** [comment]
This already appears to be set in our base AMI (see lines 262-265 of `/opt/tomcat6/conf/web.xml`).

**Comment by andrewlkho** [comment]
Actually, this is not the default in tomcat 6.0.29.  @kenners can you please outline the steps you took (customisations) that resulted in the tomcat install in the AMI?

**Comment by kenners** [comment]
Yep, sure. Essentially, applied the following patch to the default `conf/web.xml` file:

``` diff

diff --git a/web.xml b/web.xml
index e2b60ac..246cb9f 100644
--- a/web.xml
+++ b/web.xml
@@ -259,7 +259,11 @@
             <param-name>xpoweredBy</param-name>
             <param-value>false</param-value>
         </init-param>
-        <load-on-startup>3</load-on-startup>
+   <init-param>
+       <param-name>enablePooling</param-name>
+       <param-value>false</param-value>
+   </init-param>     
+   <load-on-startup>3</load-on-startup>
     </servlet>
```

I've also [provided a Gist](https://gist.github.com/2942469) with the default and patched version of web.xml.

**Comment by andrewlkho** [comment]
Documented in the kasha wiki.
