### ISSUE TITLE
Location and address

### ISSUE THREAD

**Issue by Gulfa** [uamuzibora/nafasi#19]
Need to determine how to import the uamuzibora address into OpenMRS.

In the Uamuzibora database we store:
location_id
village
home
nearest_church
nearest_school
nearest_health_centre
nearest_major_landmark

This needs to be translated into:
address1
address2
city_village
state_province
postal_code
country
longitude,latitude

Any suggestions welcome!

**Comment by kenners** [comment]
I was wondering when this would come up.

I'll have a think about this today.

Wonder if @johnhaskew has any ideas as to how much of the location
info we actually need to preserve?

**Comment by johnhaskew** [comment]
@Gulfa @kenners so we cannot create / delete these address variables within OpenMRS? These are fixed?

Looking at the uamuzi bora record, one address is listed as "Postal Address". @Gulfa to which variable does this link to in your list of uamuzi bora address variables above, is it home?

The best is to move whichever is listed as "Postal Address" in uamuzi bora to address1 and village to city_village such that:

home = address1
village = city_village

I think location_id (but the associated name, not the id number), nearest_church, nearest_school, nearest_health_centre, nearest_major_landmark should move to new variables that we create under patient attributes (see Admin -> Person -> Manage Person Attribute Types) - which I know we can edit.

Is this doable? Please also refer to Person Attributes wiki page.

**Comment by johnhaskew** [comment]
@Gulfa @kenners please also note the treatment supporter name, relationship, address and telephone number within patient profile should be included within patient attributes also as well as those I have listed under the medical informations issue @Gulfa created

**Comment by kenners** [comment]
Just come across this:
https://wiki.openmrs.org/display/docs/Address+Hierarchy+Module

I think [Person Attributes](https://wiki.openmrs.org/display/docs/Managing+Person+Attribute+Types) that @johnhaskew mentioned are less well suited to location data, but could be workable for Treatment supporter data.

**Comment by Gulfa** [comment]
That module looks quite promising. Do we want to go down that route?

As for treatment supporter I suggest we just create the treatment supporter as a new person with the information about them associated with their record and then create a treatment supporter relationship between the patient and the supporter.

**Comment by kenners** [comment]
All done: uamuzibora/fly-south@91e2255 
:satisfied:
