### ISSUE TITLE
OpenMRS Clinical Summary

### ISSUE THREAD

**Issue by johnhaskew** [uamuzibora/nafasi#2]
Clinical Summary creates "View Summary" link on the dashboard which generate a pdf template summary of the patient.

The templates are created in "Manage Templates" administration for the Clinical Summary module and use Velocity and XSLT templates. 

We can simply adapt those already designed for AMPATH (see wiki).

**Comment by kenners** [comment]
**Not done** during July 2012 visit due to time.

Should probably look at implementing this for Autumn 2012.

@Gulfa: Fancy taking a look?

@johnhaskew: Can you provide links to specific examples and also document exactly what you envisage in [our wiki](https://github.com/uamuzibora/nafasi/wiki)
