### ISSUE TITLE
Burn Ubuntu 12.04 LTS server 64 bit CD/DVD images

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#20]
Burn install discs (with duplicates) for offline install of Ubuntu onto the server in Kakamega.

Undecided whether we need burn full install discs or only netinstall discs considering we'll be taking an apt-repo VM (see #17) with us.

What does @andrewlkho think?

**Comment by andrewlkho** [comment]
As discussed we will want both a netinst CD plus the full DVDs.

**Comment by andrewlkho** [comment]
Looking into this, there [appear to be](http://releases.ubuntu.com/precise/) two well-publicised CD images for a given architecture: the live CD and the alternate install CD.  The alternate install CD is a non-graphical install which provides for certain "specialist" situations.  Crucially, it allows for LVM and RAID partitioning, so it looks like this is the one we want.

I would, however, prefer just a small net install CD (particularly if we are going to go through the effort of bringing an apt mirror with us (#17)).  There is a minimal CD [available](https://help.ubuntu.com/community/Installation/MinimalCD), although for some reason it's significantly less well publicised.  I'll have a play with both and see how much the install differs.

**Comment by kenners** [comment]
I'd agree with using the alternate install CD - previously we used the alternative install disc for Debian for precisely the reasons you outline.

i guess it all hinges on whether the minimal install CD allows us to create the LVM/RAID setup we need.

**Comment by kenners** [comment]
Done.
