### ISSUE TITLE
Download to USB stick binary install of Apache Tomcat 6.0.29

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#21]
As specified by [OpenMRS install instructions](https://wiki.openmrs.org/display/docs/Step+3+-+Install+Tomcat) this specific version of Tomcat is required.

Download from here: http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.29/bin/apache-tomcat-6.0.29.tar.gz

**Comment by andrewlkho** [comment]
This should also include an offline copy of the aforelinked wiki (everything under the "Implementer documentation") part.

**Comment by andrewlkho** [comment]
According to devs in the IRC channel, we may be able to use what's in the apt repository:

> 2012-06-23T20:57+0100 <ourmaninthebar> Hi, does anyone know whether OpenMR` 1.9.0 requires the specific version of Apache Tomcat 6.0.29 (as OpenMRS 1.8.3 required), or whether it will run stably on Tomcat 7.0.26 or 6.0.35 (packages as supplied in Ubuntu 12.04's repos)?2012-06-23T21:02+0100 -!- maurya 2012-06->23T21:17+0100 <dkayiwa> hi ourmaninthebar         2012-06-23T21:17+0100 <ourmaninthebar> hey
> 2012-06-23T21:17+0100 <dkayiwa> ourmaninthebar: it can run on both
> 2012-06-23T21:17+0100 <ourmaninthebar> so will run fine on a standard install of Tomcat7 from Ubuntu 12.04's repo (apt-get install tomcat7)?
> 2012-06-23T21:18+0100 <dkayiwa> ourmaninthebarR  yes
> 2012-06-23T21:18+0100 <ourmaninthebar> awesome, thankyou

**Comment by kenners** [comment]
Lets make sure we include Tomcat7 package in our apt-mirror :)

**Comment by andrewlkho** [comment]
As we're just doing `apt-get tomcat7` it is no longer necessary to include a copy of the tomcat binary on the USB stick.
