### ISSUE TITLE
Create init scripts for OpenMRS/Tomcat

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#23]
When running OpenMRS on our deployment machine, we'll want to start Tomcat automatically at boot time.

We should use init scripts for this.

At the moment, on our Bifrost test rig, we call the following script to launch Tomcat:
`$ /opt/tomcat6/bin/startup.sh`

@andrewlkho: I'm guessing you're best placed to look into this. Could you take a look?

**Comment by andrewlkho** [comment]
As discussed we will want to work out what minimum privileges are required for Tomcat to run properly.

**Comment by andrewlkho** [comment]
Now that we are using stock tomcat7 from the ubuntu apt repository, an install script is automatically setup in /etc/init.d/tomcat7 which works.
