### ISSUE TITLE
Information in medical_informations table

### ISSUE THREAD

**Issue by Gulfa** [uamuzibora/nafasi#24]
Need to decide how to import most of the information from the medical_informations table into openMRS.

The following fields are currently in the medical_informations table in the uamuzibora database.
hiv_positive_date
hiv_positive_test_location_id
hiv_positive_clinic_start_date
hiv_positive_who_stage
art_naive
art_service_type_id
art_first_start_date
art_eligibility_date
art_indication_id
transfer_in_date
transfer_in_district_id
transfer_in_facility
transfer_out_date
transfer_out_event
date_pep_start
pep_reason_id
art_eligible_who_stage
art_eligible_cd4
art_start_weight
art_start_height
art_start_who_stage
art_second_start_date
art_second_line_reason_id
drug_allergies

One suggestion could be to take either the art_eligible or hiv_positive data and use this to create an Initial encounter type. Whit all the data as observations. If we take the hiv_positive as the initial encounter type we might want to create a special encounter type for art eligibility. 

What do we want to do about the transfer in and out ? Is this something we have concepts for and can use the encounter/observations tables or could we use person_attributes?

**Comment by kenners** [comment]
I'll take a look at this @Gulfa and get back to you later.

**Comment by johnhaskew** [comment]
@Gulfa @kenners yes I think some of these should be created under patient attributes, again please see wiki page that I started on this topic.
1. Within Person Attributes:

Date confirmed HIV positive = hiv_positive_date
Where? = hiv_positive_test_location_id (NAME)
Date enrolled in HIV Care = hiv_positive_clinic_start_date
WHO Stage = hiv_positive_who_stage
Any Known Drug Allergies = drug_allergies
Date medically eligible for ARV therapy = art_eligibility_date
Eligible through (multiple select)
      WHO Stage = art_eligible_who_stage
      CD4 Count = art_eligible_cd4
WHO stage = art_start_who_stage
Weight = art_start_weight
Height = art_start_height
1. Others variables will be created eg.

Program enrollment date for "HIV care" = hiv_positive_clinic_start_date
Program enrollment date for "HIV treatment" = art_first_start_date
1. Variables not needed (see wiki page):

art_naive
art_service_type_id
date_pep_start
pep_reason_id
1. Variables I do not think are needed (we can remove if you guys are happy)

transfer_in_date
transfer_in_district_id
transfer_in_facility
transfer_out_date
transfer_out_event

art_second_start_date
art_second_line_reason_id

**Comment by Gulfa** [comment]
I agree that some of these things could be stored in patient attributes, but that we should not store variables like weight, height and cd4 as person attributes. Since we already will be using encounters and observations for storing this data I think it is better to create a new encounter type named something like ArtStart.

**Comment by kenners** [comment]
Didn't need all of the data fields as described above in the end. Finished thing here: uamuzibora/fly-south@91e2255
