### ISSUE TITLE
Create openmrs-runtime.properties file for server deploy

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#25]
When OpenMRS starts, it looks for `openmrs-runtime.properties` which contain database login details and a few other parameters.

OpenMRS looks for this file in a couple of default locations (on our test instances it's in `/root/.OpenMRS/openmrs-runtime.properties`)

Details here: https://wiki.openmrs.org/display/docs/Overriding+OpenMRS+Default+Runtime+Properties

Our usual config is this:

```
module.allow_web_admin=true
connection.url=jdbc:mysql://localhost:3306/openmrs?autoReconnect=true&sessionVariables=storage_engine=InnoDB&useUnicode=true&characterEncoding=UTF-8
connection.username=openmrs
auto_update_database=false
connection.password=<password>
```

We should create this file in the root of [nafasi](https://github.com/uamuzibora/nafasi) to version control it (apart from passwords), and we should agree where we're going to put it on our deployment server (`/root` or declare it in the `OPENMRS_RUNTIME_PROPERTIES_FILE` environmental)?

@Gulfa, @andrewlkho: thoughts?

**Comment by andrewlkho** [comment]
As part of this, we should look into whether or not Tomcat can connect to a MySQL socket rather than to a TCP port.

**Comment by andrewlkho** [comment]
We'll want to commit the config to the kasha repository.

**Comment by andrewlkho** [comment]
This configuration is documented in the kasha wiki.
