### ISSUE TITLE
Update backup scripts (hero) to work for OpenMRS

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#26]
We need to review our [backups system](https://github.com/uamuzibora/hero) and check it works for our new stack.

In particular, is there a reason why we can't continue to do backups to the netbooks and get backups emailed on, as we have been doing?

@andrewlkho: Would you be willing/available to look at this?

**Comment by andrewlkho** [comment]
This will also require documentation on the kasha wiki about what cronjobs need to be set up.  Much of this can be pulled from the [old wiki](http://dev.uamuzibora.com/).

**Comment by andrewlkho** [comment]
We will want to make sure that logrotate is set to something sensible, bearing in mind that we may not be able to access in-country backups for several months at a time (i.e. not a fortnightly rotation!).

**Comment by kenners** [comment]
Done. See uamuzibora/hero@343619b562451dae806be6283fc6c6220cf3c30a
