### ISSUE TITLE
Add OpenMRS Reports

### ISSUE THREAD

**Issue by johnhaskew** [uamuzibora/nafasi#3]
The final module which we need to understand well for Uamuzi Bora is the reporting module.
https://wiki.openmrs.org/display/docs/Reporting+Module

We can use it to export data as csv.

We will need to create standard aggregate reports for MoH reports using this module

**Comment by johnhaskew** [comment]
I have a fair idea now of how to use excel templates of MoH standard reports and to create custom period indicator reports using these templates within OpenMRS. I think this will be the easiest away for MoH for receive the period reports they require. We can complete row-by-row registers in the same manner.

@kenners please let me know when I can access the deployment version to include this reporting standard or whether I send the excel templates to you to include.

Please note you will need to manually create and define dimensions/indicators using the OpenMRS UI if you want to do it yourself.

**Comment by kenners** [comment]
@johnhaskew should now be able to begin to play with this using his local copy of OpenMRS and the anonymised data set.

If we want to add reports to the **Kakamega** installation, @johnhaskew please reopen this issue once you've got finalised some specific reports.
