### ISSUE TITLE
UPN

### ISSUE THREAD

**Issue by johnhaskew** [uamuzibora/nafasi#30]
The UPN number has changed.

The 7th and 8th digits (always `57`) have been removed so the UPN is 11 digits, not 13 in length.

For example: `15915157-06507`

becomes: `159151-06507`

Please can we account for this as we migrate across to OpenMRS.

**Comment by kenners** [comment]
I'm adding the schema for the UPN this afternoon.

**Comment by kenners** [comment]
Ok @Gulfa: you're up ;)

You've now got the UPN as an available identifier in OpenMRS (and is set to be required for all patients).
