### ISSUE TITLE
Encounters and observations

### ISSUE THREAD

**Issue by Gulfa** [uamuzibora/nafasi#33]
We need to import all the results from UB into openMRS

After studying the schema carefully I think this should actually be fairly straight forward.

We crate one encounter which is associated with a patient and then each encounter can have multiple observations.

In UB we do not have the encounter, but I think we can just take all results from the same day and put them into one encounter. 

It looks like each encounter is connected to a form which is connected to an encounter type.  At this stage I just need to know which forms and encounter types we plan on creating.

**Comment by kenners** [comment]
Agree with all of the above.

You'll likely need to wait until @johnhaskew and myself are done with
checking #32 and built the forms 6 or so forms we're going to use.

**Comment by johnhaskew** [comment]
@Gulfa @kenners I have updated the Adult Return Clinic form and SWS forms on the wiki to include updated codes linked to concepts.

@kenners there is still an error when selecting any concepts we created. Not sure why.

I have sent a commit of these changes to a branch named john.

@kenners it is going to be highly improbably that I can select particular lines of code that I have modified with each commit. A further 20,000 lines were added in the last commit (presumably as I had to create an example patient -- may help to include an example patient in the first place).

**Comment by kenners** [comment]
Thanks @johnhaskew - I'll look into it the problem with the concepts
(can we keep discussion related to that problem on this thread: #32)

**Comment by johnhaskew** [comment]
@kenners @Gulfa I sent this information in an email and reproduce here.

I updated questions to the SWS survey (Q15-18) in the wiki today. I tried to load the most recent commit I made yesterday (bifrost.py --start=1f36cbfa53) to update these changes in the concept dictionary but for some reason cannot find any concepts in this version of the dictionary. I don't know what I am doing wrong.

I am now away from tomorrow morning until 20th June (my brother arrives today) so will not be able to make any further contributions before the 20th.

@Kenrick - please could you update the concepts for SWS questions below.

**Comment by kenners** [comment]
All done: uamuzibora/fly-south@91e2255 
:satisfied:
