### ISSUE TITLE
Secure networking with fail2ban or similar

### ISSUE THREAD

**Issue by andrewlkho** [uamuzibora/nafasi#39]
Given that we're not connected to the internet this is considered an enhancement rather than a requirement at this stage.

**Comment by kenners** [comment]
I suggest we consider deploying this when @Gulfa goes out in September. That way we're premptively covered for if/when we're no longer airgapped from the internet.

@Gulfa: Happy to do this in September?

@andrewlkho: Can you document an install/deployment checklist on [the wiki](https://github.com/uamuzibora/kasha/wiki) when convenient?

**Comment by andrewlkho** [comment]
This issue has been moved over to uamuzibora/kasha#16.
