### ISSUE TITLE
Install smartmon package and run regularly as cronjob

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#40]
We should monitor the smart status of our disks.

**Comment by kenners** [comment]
**Not done** in July 2012 visit.

Smart status was checked using the PERC BIOS prior to new install.

I suggest we consider investigating whether we can get smartmon setup in September and also run it regularly as a cronjob.

As we're getting log files back with the db dumps, it means we can get some forewarning of when disks may need to be replaced.

The [Ubuntu manpage](http://manpages.ubuntu.com/manpages/precise/man8/smartctl.8.html) suggests that smartmon plays nice with Dell PERC controllers (we have a **Dell PERC 6/i** controller):

> megaraid,N  -  [Linux  only]  the device consists of one or more
> SCSI/SAS disks connected to a  MegaRAID  controller.   The  non-
> negative  integer N (in the range of 0 to 127 inclusive) denotes
> which disk on the controller is monitored.  Use syntax such as:
> smartctl -a -d megaraid,2 /dev/sda
> smartctl -a -d megaraid,0 /dev/sdb
> This interface will also work for Dell  PERC  controllers.   The
> following /dev/XXX entry must exist:
> For PERC2/3/4 controllers: /dev/megadev0
> For PERC5/6 controllers: /dev/megaraid_sas_ioctl_node

@Gulfa: Happy looking at this for September?

**Comment by andrewlkho** [comment]
This issue has been moved to uamuzibora/kasha#17.
