### ISSUE TITLE
Disable pooling in Tomcat

### ISSUE THREAD

**Issue by andrewlkho** [uamuzibora/nafasi#52]
From Kenrick:

> Could you quickly investigate how we disable pooling in the JSP servlet definition in our $TOMCAT_HOME/conf/web.xml config file as per: https://wiki.openmrs.org/display/docs/Performance+Tuning
> 
> The instructions at the wiki above are referencing Tomcat6, and we're using Tomcat7 - the web.xml file looks significantly different to what we've got. I'm not entirely sure where we go with that.

**Comment by kenners** [comment]
Might have actually sorted this today - actually turns out to not be that dissimilar.

**Comment by kenners** [comment]
@andrewlkho documented this in [the wiki](https://github.com/uamuzibora/kasha/wiki/Web-stack).
