### ISSUE TITLE
Performance tune MySQL

### ISSUE THREAD

**Issue by andrewlkho** [uamuzibora/nafasi#53]
From Kenrick:

> Further, in our deployment checklist, I need something about MySQL InnoDB tuning, including setting a sensible innodb_buffer_pool_size in /etc/my.cnf to optimise our db queries.

**Comment by kenners** [comment]
**Not done** during July 2012 visit.

This needs to be rescheduled for Autumn 2012 visit (maybe by @Gulfa?), and will likely be better once OpenMRS has actually been used for a bit so we have some analytics on db load/performance.

Also: [mysqltuner.pl](http://mysqltuner.pl) looks promising.

**Comment by andrewlkho** [comment]
This issue has been split into multiple issues in the kasha repository with the mysql tag.
