### ISSUE TITLE
Should we move the Ops tasks into Kasha's issues?

### ISSUE THREAD

**Issue by kenners** [uamuzibora/nafasi#55]
@Gulfa, @andrewlkho: Going forwards, would it be appropriate to move the Ops tasks into Kasha's issues, rather than having them jumbled up with our bugs/enhancements for Nafasi?

**Comment by andrewlkho** [comment]
I think we should.  Ops tasks are pretty specific to kasha and deserve a separate namespace to our actual software.  If @gulfa and @kenners agree then I'll look into porting them over.

**Comment by kenners** [comment]
I think we should do this.

@andrewlkho: Can you sort this at your convenience?

**Comment by kenners** [comment]
@andrewlkho: Nudge?

**Comment by andrewlkho** [comment]
Done.  Unfortunately github does not support moving of issues (including their comments), so I had to recreate them and cross-reference the old issue.
